spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.H2Dialect


server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

jwt:
  secret: VXNlclJlZnVuZENhbGN1bGF0b3I=

springdoc:
  swagger-ui:
    path: /3o3/swagger.html

scrap:
  api-key: aXC8zK6puHIf9l53L8TiQg==
  api-url: https://codetest-v4.3o3.co.kr/scrap

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace